spring.datasource.url=jdbc:postgresql://${DB_HOST:dpg-d97nn158nd3s73e43leg-a}:${DB_PORT:5432}/${DB_NAME:airbeam}
spring.datasource.username=${DB_USER:fuzailnoor}
spring.datasource.password=${DB_PASSWORD:mezfBNwHR4NznpwwUFufxUN3iWHtKQH2}
spring.jpa.hibernate.ddl-auto=update
