# ===============================
# SERVER
# ===============================
server.port=${PORT:8082}
server.address=0.0.0.0

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://p2p_db_hi22_user:T24uzXfUN9FX5sglb4zILsX3TpW7PfLP@dpg-d7qhlb3eo5us73c7b29g-a/p2p_db_hi22
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# FILE STORAGE PATH
# ===============================
file.storage.path=${FILE_STORAGE_PATH:storage/}

# ===============================
# MULTIPART CONFIG (for file upload)
# ===============================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.enabled=true
