# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/p2p_db
spring.datasource.username=root
spring.datasource.password=alien

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FILE STORAGE PATH
# ===============================
file.storage.path=storage/

# ===============================
# MULTIPART CONFIG (for file upload)
# ===============================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.enabled=true
